sudo: true
language: node_js
node_js:
  - '8'
cache: yarn
addons:
  apt:
    packages:
      - sshpass
jobs:
  include:
    - stage: before
      install:
        - npm i npminstall && npminstall
      script: 
        - npm run test
    - stage: build
      script: 
        - npm run build
    - stage: deploy
      script:
        - echo '123'
      branches:
        only:
          - master